// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dngeekrmjgecebmltxhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZ2Vla3JtamdlY2VibWx0eGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTY0NzIsImV4cCI6MjA3NDA5MjQ3Mn0.RW28xpOuOjI2EvxsxI3uWD_QS39Tk3RjygP8PLBuESo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});